# Базовые настройки
title: pictura abstracta
email: example@example.com
description: >-
  абстрактная интерьерная живоаись Марины Балик
baseurl: "/"
url: "https://picabs.ru" 
twitter_username: picabs
github_username:  picabsart

# Тема
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Настройка коллекций
collections:
  paintings:
    output: true
    permalink: /painting/:name/
