# Базовые настройки
title: Pictura Abstracta
email: example@example.com
description: >-
  Абстрактная интерьерная живопись художницы Марины Балик. Купить картину для дома или офиса онлайн. Авторские работы в стиле абстракции. Украшение интерьера с душой. Заказ через маркетплейсы. Выпускница Строгановского университета.
keywords: абстрактная живопись, интерьерная живопись, картины для дома, картины для интерьера, купить картину онлайн
baseurl: "/"
url: "https://picabs.ru" 
logo: "/assets/picabs_logo.png"
github_username:  picabsart

# Тема
theme: minima 
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Настройка коллекций
collections:
  paintings:
    output: true
    permalink: /painting/:name/
  articles:
    output: true
    permalink: /article/:name/
