title: Picabs - Художник
email: example@example.com
description: >-
  Лучшие картины маслом и акварелью от художника Picabs
baseurl: "/"
url: "https://picabs.ru" 
twitter_username: picabs
github_username:  picabsart
theme: minima
plugins:
  - jekyll-feed
