title: My Awesome Site
email: your_email@example.com
description: >-
  Описание моего сайта
baseurl: "" # если это picabsart.github.io — оставь пустым
url: "" # GitHub сам определит URL
author: Your Name

# Настройки пагинации
paginate: 5
paginate_path: "/blog/page:num/"

# SEO
logo: "/assets/images/logo.png"

# Плагины
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag