title: Picabs - абстрактная интерьерная живопись
email: example@example.com
description: >-
  Абстрактная интерьерная живоаись Марины Балик
baseurl: "/"
url: "https://picabs.ru" 
twitter_username: picabs
github_username:  picabsart
theme: minima
plugins:
  - jekyll-feed
