# Базовые настройки
title: Pictura Abstracta
email: example@example.com
description: >-
  Абстрактная интерьерная живопись Марины Балик
baseurl: "/"
url: "https://picabs.ru" 
logo: "/assets/picabs_logo.png"
twitter_username: picabs
github_username:  picabsart

# Тема
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Настройка коллекций
collections:
  paintings:
    output: true
    permalink: /painting/:name/
  articles:
    output: true
    permalink: /article/:name/
